name: Validate HACS Config

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate repository with HACS
        uses: hacs/action@main
        with:
          category: integration
